name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      output1: 10
      output2: "output-2 local"
    steps:
    - name: checkout
      id: checkout
      run: echo "checkout"
      
    - name: build image
      id: build-image
      run: echo "image build"
      
    - name: push image
      id: push-image
      run: echo "image pushed"
      
    - name: build
      id: build
      run: echo "build"
  
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    steps:
    - name: pre-deploy
      id: pre-deploy
      run: | 
        echo "pre-deploy"
        echo ${{ needs.build.outputs.output2 }}
    - name: deploy
      id: deploy
      if: needs.build.outputs.output1 == 10
      run: echo "value 10 it worked"
      
    - name: post-deploy
      id: post-deploy
      if: needs.build.outputs.output1 != 10
      run: echo "value is not 10 it not worked"
