name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
    

jobs:
  admin:
    runs-on: ubuntu-latest
    steps:
    - run: echo "admin"
  
  app:
    runs-on: ubuntu-latest
    steps:
    - run: echo "app"
    
  buy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "buy"
    
  speed:
    runs-on: ubuntu-latest
    steps:
    - run: echo "speed"
    
  all:
    runs-on: ubuntu-latest
    needs: [admin, app, buy, speed]
    steps:
    - run: echo "Looks good"
